"""add_exercise_folders_and_course_groups

Revision ID: 95524b0b86f0
Revises: add_email_unique_20251125
Create Date: 2025-11-25 16:29:11.622712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '95524b0b86f0'
down_revision: Union[str, Sequence[str], None] = 'add_email_unique_20251125'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exercise_folders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('therapist_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['therapist_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('course_group_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_group_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['course_group_id'], ['course_groups.id'], ),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_group_id', 'course_id', name='uniq_course_group_assignment')
    )
    op.drop_table('student_exercises')
    op.add_column('course_exercises', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('course_exercises', 'publish_at')
    op.drop_column('course_exercises', 'published')
    op.drop_index(op.f('ux_course_students_unique'), table_name='course_students')
    op.add_column('exercises', sa.Column('folder_id', sa.Integer(), nullable=True))
    op.add_column('exercises', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'exercises', 'exercise_folders', ['folder_id'], ['id'])
    op.drop_column('exercises', 'audio_url')
    op.drop_constraint(op.f('uq_users_email'), 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_users_email'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.add_column('exercises', sa.Column('audio_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'exercises', type_='foreignkey')
    op.drop_column('exercises', 'deleted_at')
    op.drop_column('exercises', 'folder_id')
    op.create_index(op.f('ux_course_students_unique'), 'course_students', ['course_id', 'student_id'], unique=True)
    op.add_column('course_exercises', sa.Column('published', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('course_exercises', sa.Column('publish_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('course_exercises', 'deleted_at')
    op.create_table('student_exercises',
    sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('exercise_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=16), server_default=sa.text("'ASSIGNED'::character varying"), autoincrement=False, nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('student_exercises_course_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], name=op.f('student_exercises_exercise_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('student_exercises_student_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('course_id', 'exercise_id', 'student_id', name=op.f('student_exercises_pkey'))
    )
    op.drop_table('course_group_assignments')
    op.drop_table('exercise_folders')
    op.drop_table('course_groups')
    # ### end Alembic commands ###
